import js from "@eslint/js";
import reactHooks from "eslint-plugin-react-hooks";
import globals from "globals";
import tseslint from "typescript-eslint";
import { defineConfig, globalIgnores } from "eslint/config";


// Conventions enforced mechanically (see .ai/rules/conventions.md)
const conventions = {
  files: ["**/*.{ts,tsx}"],
  rules: {
    "no-console": "warn",
    complexity: ["warn", 10],
    "max-params": ["warn", 4],
    "max-classes-per-file": ["warn", 1],
    eqeqeq: ["error", "always"],
    "max-lines": ["warn", { max: 300, skipBlankLines: true, skipComments: true }],
    "@typescript-eslint/consistent-type-imports": "error",
    "@typescript-eslint/naming-convention": [
      "error",
      { selector: "typeLike", format: ["PascalCase"] },
      { selector: "variable", format: ["camelCase", "PascalCase", "UPPER_CASE"], leadingUnderscore: "allow" },
      { selector: "function", format: ["camelCase", "PascalCase"] },
    ],
  },
};

// Cross-feature imports must go through the feature surface (@/features/<name>)
const featureSurface = {
  files: ["apps/web/**/*.{ts,tsx}"],
  rules: {
    "no-restricted-imports": [
      "error",
      { patterns: [{ group: ["@/features/*/*"], message: "Import a feature only through its surface: @/features/<name>." }] },
    ],
  },
};

export default defineConfig([
  // schema.d.ts is generated by npm run contract:gen; apps/api is Python
  globalIgnores(["**/dist/**", "**/node_modules/**", ".ai/**", "apps/api/**", "apps/web/src/lib/api/schema.d.ts"]),
  js.configs.recommended,
  tseslint.configs.recommended,
  conventions,
  featureSurface,
  {
    files: ["apps/web/**/*.{ts,tsx}"],
    extends: [reactHooks.configs.flat.recommended],
    languageOptions: { globals: globals.browser },
  },
  {
    files: ["scripts/**/*.mjs", "*.config.{ts,mjs}"],
    languageOptions: { globals: globals.node },
  },
]);
